<?
$arTooltips = array(
	"FORUM_ID" => GetMessage("FORUM_ID_TIP"),
	"IBLOCK_TYPE" => GetMessage("IBLOCK_TYPE_TIP"),
	"IBLOCK_ID" => GetMessage("IBLOCK_ID_TIP"),
	"ELEMENT_ID" => GetMessage("ELEMENT_ID_TIP"),
	"POST_FIRST_MESSAGE" => GetMessage("POST_FIRST_MESSAGE_TIP"),
	"POST_FIRST_MESSAGE_TEMPLATE" => GetMessage("POST_FIRST_MESSAGE_TEMPLATE_TIP"),
	"URL_TEMPLATES_READ" => GetMessage("URL_TEMPLATES_READ_TIP"),
	"URL_TEMPLATES_DETAIL" => GetMessage("URL_TEMPLATES_DETAIL_TIP"),
	"URL_TEMPLATES_PROFILE_VIEW" => GetMessage("URL_TEMPLATES_PROFILE_VIEW_TIP"),
	"MESSAGES_PER_PAGE" => GetMessage("MESSAGES_PER_PAGE_TIP"),
	"PAGE_NAVIGATION_TEMPLATE" => GetMessage("PAGE_NAVIGATION_TEMPLATE_TIP"),
	"DATE_TIME_FORMAT" => GetMessage("DATE_TIME_FORMAT_TIP"),
	"PATH_TO_SMILE" => GetMessage("PATH_TO_SMILE_TIP"),
	"USE_CAPTCHA" => GetMessage("USE_CAPTCHA_TIP"),
	"PREORDER" => GetMessage("PREORDER_TIP"),
	"DISPLAY_PANEL" => GetMessage("DISPLAY_PANEL_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
);
?>